# Generated by Django 5.2.10 on 2026-01-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'idempotency_key',
                    models.CharField(
                        db_index=True,
                        help_text='Unique key for idempotent transaction processing',
                        max_length=255,
                    ),
                ),
                (
                    'description',
                    models.TextField(help_text='Transaction description'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('POSTED', 'Posted'),
                            ('REVERSED', 'Reversed'),
                            ('VOIDED', 'Voided'),
                        ],
                        db_index=True,
                        default='POSTED',
                        help_text='Transaction status',
                        max_length=20,
                    ),
                ),
                (
                    'posted_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='When the transaction was posted',
                        null=True,
                    ),
                ),
                (
                    'created_by',
                    models.CharField(
                        blank=True,
                        help_text='User who created the transaction',
                        max_length=255,
                    ),
                ),
                (
                    'version',
                    models.IntegerField(
                        default=0, help_text='Optimistic locking version number'
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='The organization that owns this record',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='common.organization',
                    ),
                ),
                (
                    'reversed_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='Reference to reversing transaction if this was reversed',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reverses',
                        to='journal.journalentry',
                    ),
                ),
            ],
            options={
                'db_table': 'journal_journalentry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'entry_type',
                    models.CharField(
                        choices=[('DR', 'Debit'), ('CR', 'Credit')],
                        help_text='Debit or Credit',
                        max_length=2,
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Entry amount',
                        max_digits=15,
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, help_text='Line-specific description'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'account',
                    models.ForeignKey(
                        help_text='Account for this entry line',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='journal_entries',
                        to='accounts.account',
                    ),
                ),
                (
                    'journal_entry',
                    models.ForeignKey(
                        help_text='Parent journal entry',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entries',
                        to='journal.journalentry',
                    ),
                ),
            ],
            options={
                'db_table': 'journal_journalentryline',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionIdempotencyCache',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'idempotency_key',
                    models.CharField(db_index=True, max_length=255),
                ),
                (
                    'request_hash',
                    models.CharField(
                        help_text='Hash of original request for validation',
                        max_length=255,
                    ),
                ),
                (
                    'journal_entry',
                    models.OneToOneField(
                        help_text='The successfully processed transaction',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='journal.journalentry',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='The organization that owns this record',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='common.organization',
                    ),
                ),
            ],
            options={
                'db_table': 'journal_idempotency_cache',
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(
                fields=['idempotency_key'],
                name='journal_jou_idempot_c23055_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(
                fields=['status'], name='journal_jou_status_baee45_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(
                fields=['created_at'], name='journal_jou_created_41a2c3_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('organization', 'idempotency_key')},
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(
                fields=['journal_entry'], name='journal_jou_journal_aa71a4_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(
                fields=['account'], name='journal_jou_account_f9541f_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='transactionidempotencycache',
            unique_together={('organization', 'idempotency_key')},
        ),
    ]
