# Generated by Django 5.2.10 on 2026-01-17 11:41

import django.db.models.deletion
from django.db import migrations, models

import src.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'code',
                    models.CharField(
                        db_index=True,
                        help_text='Unique account identifier (e.g., 1000-CASH)',
                        max_length=20,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Account name (e.g., M-Pesa Cash Account)',
                        max_length=255,
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Detailed account description',
                        null=True,
                    ),
                ),
                (
                    'account_type',
                    models.CharField(
                        choices=[
                            ('ASSET', 'Asset'),
                            ('LIABILITY', 'Liability'),
                            ('EQUITY', 'Equity'),
                            ('INCOME', 'Income'),
                            ('EXPENSE', 'Expense'),
                        ],
                        db_index=True,
                        help_text='Type of account: ASSET, LIABILITY, EQUITY, INCOME, EXPENSE',
                        max_length=20,
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        choices=[
                            ('KES', 'Kenyan Shilling'),
                            ('UGX', 'Ugandan Shilling'),
                            ('USD', 'United States Dollar'),
                        ],
                        default='KES',
                        help_text='Primary currency for this account',
                        max_length=3,
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Whether account is active and can be used',
                    ),
                ),
                (
                    'is_control_account',
                    models.BooleanField(
                        default=False,
                        help_text='Control accounts are parent accounts only (no transactions)',
                    ),
                ),
                (
                    'is_system_account',
                    models.BooleanField(
                        default=False,
                        help_text='System accounts cannot be modified or deleted',
                    ),
                ),
                (
                    'identifiers',
                    models.TextField(
                        blank=True,
                        help_text='Comma-separated custom identifiers for system tagging',
                        validators=[
                            src.accounts.models.validate_account_identifiers
                        ],
                    ),
                ),
                (
                    'version',
                    models.IntegerField(
                        default=0, help_text='Optimistic locking version number'
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='The organization that owns this record',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='common.organization',
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        help_text='Parent account for hierarchical structure',
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='children',
                        to='accounts.account',
                    ),
                ),
            ],
            options={
                'db_table': 'accounts_account',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'balance_date',
                    models.DateField(
                        db_index=True, help_text='Date of balance snapshot'
                    ),
                ),
                (
                    'balance',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Account balance on this date',
                        max_digits=15,
                    ),
                ),
                (
                    'debit_total',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Total debits up to this date',
                        max_digits=15,
                    ),
                ),
                (
                    'credit_total',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Total credits up to this date',
                        max_digits=15,
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='balance_snapshots',
                        to='accounts.account',
                    ),
                ),
            ],
            options={
                'db_table': 'accounts_balance',
                'ordering': ['-balance_date'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(
                fields=['code'], name='accounts_ac_code_3fcb09_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(
                fields=['account_type'], name='accounts_ac_account_659999_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(
                fields=['is_active'], name='accounts_ac_is_acti_b52bc0_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(
                fields=['parent'], name='accounts_ac_parent__6c7ad0_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('organization', 'code', 'currency')},
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(
                fields=['account', 'balance_date'],
                name='accounts_ba_account_152e95_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(
                fields=['balance_date'], name='accounts_ba_balance_61c8dc_idx'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('account', 'balance_date')},
        ),
    ]
