# Generated by Django 5.2.10 on 2026-01-17 11:41

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='The organization that owns this record',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='common.organization',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'capital_account_code',
                    models.CharField(
                        default='2110',
                        help_text='Account code representing lender capital (liability).',
                        max_length=20,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='The organization that owns this record',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='common.organization',
                    ),
                ),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'principal_amount',
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    'currency',
                    models.CharField(
                        choices=[
                            ('KES', 'Kenyan Shilling'),
                            ('UGX', 'Ugandan Shilling'),
                            ('USD', 'United States Dollar'),
                        ],
                        default='KES',
                        max_length=3,
                    ),
                ),
                (
                    'interest_rate',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Annual interest rate (percentage).',
                        max_digits=5,
                    ),
                ),
                ('term_months', models.PositiveIntegerField(default=12)),
                (
                    'origination_fee',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('APPROVED', 'Approved'),
                            ('DISBURSED', 'Disbursed'),
                            ('ACTIVE', 'Active'),
                            ('REPAID', 'Repaid'),
                            ('DEFAULTED', 'Defaulted'),
                            ('WRITTEN_OFF', 'Written Off'),
                        ],
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                (
                    'outstanding_principal',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14
                    ),
                ),
                (
                    'accrued_interest',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14
                    ),
                ),
                (
                    'version',
                    models.PositiveIntegerField(
                        default=0, help_text='Optimistic locking version.'
                    ),
                ),
                (
                    'loans_receivable_code',
                    models.CharField(default='1210', max_length=20),
                ),
                (
                    'cash_account_code',
                    models.CharField(default='1110', max_length=20),
                ),
                (
                    'fee_receivable_code',
                    models.CharField(default='1220', max_length=20),
                ),
                (
                    'fee_income_code',
                    models.CharField(default='4210', max_length=20),
                ),
                (
                    'interest_income_code',
                    models.CharField(default='4100', max_length=20),
                ),
                (
                    'interest_receivable_code',
                    models.CharField(default='1220', max_length=20),
                ),
                (
                    'bad_debt_expense_code',
                    models.CharField(default='5100', max_length=20),
                ),
                (
                    'borrower',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='loans',
                        to='loans_management.borrower',
                    ),
                ),
                (
                    'lender',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='loans',
                        to='loans_management.lender',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='The organization that owns this record',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='common.organization',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('DISBURSEMENT', 'Disbursement'),
                            ('REPAYMENT', 'Repayment'),
                            ('WRITE_OFF', 'Write Off'),
                            ('ACCRUAL', 'Interest Accrual'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'idempotency_key',
                    models.CharField(db_index=True, max_length=100),
                ),
                ('payload', models.JSONField(default=dict)),
                (
                    'journal_entry',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='loan_events',
                        to='journal.journalentry',
                    ),
                ),
                (
                    'loan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='events',
                        to='loans_management.loan',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='The organization that owns this record',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='common.organization',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['loan', 'event_type'],
                        name='loans_manag_loan_id_a2c537_idx',
                    ),
                    models.Index(
                        fields=['idempotency_key'],
                        name='loans_manag_idempot_53aa50_idx',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=100)),
                (
                    'amount',
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    'principal_component',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14
                    ),
                ),
                (
                    'interest_component',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=14
                    ),
                ),
                (
                    'paid_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'external_reference',
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('PENDING', 'Pending'), ('POSTED', 'Posted')],
                        default='PENDING',
                        max_length=20,
                    ),
                ),
                (
                    'loan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='repayments',
                        to='loans_management.loan',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='The organization that owns this record',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(class)s_records',
                        to='common.organization',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['loan', 'paid_at'],
                        name='loans_manag_loan_id_4aa65e_idx',
                    ),
                    models.Index(
                        fields=['idempotency_key'],
                        name='loans_manag_idempot_9ca077_idx',
                    ),
                ],
                'unique_together': {('organization', 'idempotency_key')},
            },
        ),
    ]
