# Generated by Django 5.2.10 on 2026-01-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationuser',
            new_name='common_orga_organiz_97c094_idx',
            old_name='common_orga_organiz_4418df_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationuser',
            new_name='common_orga_organiz_09c0a0_idx',
            old_name='common_orga_organiz_bf5d4e_idx',
        ),
    ]
